name: Deploy AWS Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'cloudformation/**'
      - 'glue/**'
      - 'lambda/**'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-2
  DEPLOYMENT_BUCKET: ade-github-actions-artifacts-hithaish
  SOURCE_BUCKET: ade-cfn-glue-source-hithaish
  STACK_NAME: ADE-CFN-Glue-Pipeline
  GLUE_SCRIPT_KEY: glue/glue_job.py
  CFN_TEMPLATE: cloudformation/pipeline.yml
  AWS_ROLE_ARN: arn:aws:iam::157320905721:role/ADE-GitHubActions-Deploy-Role

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsDeployment
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Upload Glue script
        run: |
          aws s3 cp glue/glue_job.py \
            s3://${DEPLOYMENT_BUCKET}/${GLUE_SCRIPT_KEY}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://${CFN_TEMPLATE}

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ${CFN_TEMPLATE} \
            --stack-name ${STACK_NAME} \
            --parameter-overrides \
              GlueScriptBucket=${DEPLOYMENT_BUCKET} \
              GlueScriptKey=${GLUE_SCRIPT_KEY} \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${AWS_REGION}

      - name: Upload input CSV
        run: |
          aws s3 cp input/sample.csv \
            s3://${SOURCE_BUCKET}/input/sample.csv

      - name: Show stack outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name ${STACK_NAME} \
            --query 'Stacks[0].Outputs' \
            --output table
